name: API

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install package managers
        run: npm install -g npm yarn pnpm
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: web/clef/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('web/clef/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node
      - name: Install dependencies
        run: cd web/clef && npm ci
      - name: Lint web application
        run: cd web/clef && npm run lint
      - name: Build web frontend
        run: cd web/clef && npm run build
      - name: Build program
        run: cargo build --release
      - name: Run tests
        run: make ci-test-full
